In [ ]:
# Import des libraries
%matplotlib inline
import  numpy as np
import pandas as pd
import scipy.stats
import matplotlib.pyplot as plt

In [24]:
df = pd.read_csv('PlayGolf.csv', sep=';')

In [25]:
df

OUTLOOK TEMPERATURE HUMIDITY  WINDY PLAY GOLF
0      Rainy         Hot     High  False        No
1      Rainy         Hot     High   True        No
2   Overcast         Hot     High  False       Yes
3      Sunny        Mild     High  False       Yes
4      Sunny        Cool   Normal  False       Yes
5      Sunny        Cool   Normal   True        No
6   Overcast        Cool   Normal   True       Yes
7      Rainy        Mild     High  False        No
8      Rainy        Cool   Normal  False       Yes
9      Sunny        Mild   Normal  False       Yes
10     Rainy        Mild   Normal   True       Yes
11  Overcast        Mild     High   True       Yes
12  Overcast         Hot   Normal  False       Yes
13     Sunny        Mild     High   True        No

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   OUTLOOK      14 non-null     object
 1   TEMPERATURE  14 non-null     object
 2   HUMIDITY     14 non-null     object
 3   WINDY        14 non-null     bool  
 4   PLAY GOLF    14 non-null     object
dtypes: bool(1), object(4)
memory usage: 590.0+ bytes


In [27]:
df.shape

(14, 5)

In [43]:
def entropy(target):
    """
    une fonction qui permet 
    le calcul l'entropie
    
    """
    
    pdata = target.value_counts()
    e = scipy.stats.entropy(pdata, base = 2)
    return e

In [44]:
entropy(df['PLAY GOLF'])

0.940285958670631

In [30]:
df['PLAY GOLF'][df['PLAY GOLF']=='No'].shape

(5,)

In [31]:
df['PLAY GOLF'][df['PLAY GOLF']=='Yes'].shape

(9,)

In [32]:
df['PLAY GOLF'].unique()

array(['No', 'Yes'], dtype=object)

In [33]:
df['PLAY GOLF'].nunique()

2

In [35]:
# Table de contingence(cross tab)

pd.crosstab(df['OUTLOOK'], df['PLAY GOLF'], margins=True)

PLAY GOLF  No  Yes  All
OUTLOOK                
Overcast    0    4    4
Rainy       3    2    5
Sunny       2    3    5
All         5    9   14

In [37]:
pd.crosstab(df['TEMPERATURE'], df['PLAY GOLF'], margins=True)

PLAY GOLF    No  Yes  All
TEMPERATURE              
Cool          1    3    4
Hot           2    2    4
Mild          2    4    6
All           5    9   14

In [38]:
pd.crosstab(df['HUMIDITY'], df['PLAY GOLF'], margins=True)

PLAY GOLF  No  Yes  All
HUMIDITY               
High        4    3    7
Normal      1    6    7
All         5    9   14

In [39]:
pd.crosstab(df['WINDY'], df['PLAY GOLF'], margins=True)

PLAY GOLF  No  Yes  All
WINDY                  
False       2    6    8
True        3    3    6
All         5    9   14

In [47]:
# Encodage de la target variable
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
target = lel.fit_transform(df['PLAY GOLF'])
y = target
print(y)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [54]:
# Encodage des varibles explicatique
from sklearn.preprocessing import label_binarize
le2 = LabelEncoder()
outlook = le2.fit_transform(df['OUTLOOK'])
print(outlook)

[1 1 0 2 2 2 0 1 1 2 1 0 0 2]


In [55]:
# Encodage des varibles explicatique
from sklearn.preprocessing import label_binarize
le3 = LabelEncoder()
temp = le3.fit_transform(df['TEMPERATURE'])
print(temp)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [56]:
# Encodage des varibles explicatique
from sklearn.preprocessing import label_binarize
le4 = LabelEncoder()
humidity = le4.fit_transform(df['HUMIDITY'])
print(humidity)

[0 0 0 0 1 1 1 0 1 1 1 0 1 0]


In [57]:
# Encodage des varibles explicatique
from sklearn.preprocessing import label_binarize
le5 = LabelEncoder()
windy = le5.fit_transform(df['WINDY'])
print(windy)

[0 1 0 0 0 1 1 0 0 0 1 1 0 1]


In [62]:
X= pd.DataFrame( data = [outlook, temp, humidity, windy]).T

In [66]:
X.columns = ['OUTLOOK', 'TEMPERATURE', 'HUMIDITY', 'WINDY']

In [68]:
X

OUTLOOK  TEMPERATURE  HUMIDITY  WINDY
0         1            1         0      0
1         1            1         0      1
2         0            1         0      0
3         2            2         0      0
4         2            0         1      0
5         2            0         1      1
6         0            0         1      1
7         1            2         0      0
8         1            0         1      0
9         2            2         1      0
10        1            2         1      1
11        0            2         0      1
12        0            1         1      0
13        2            2         0      1

In [69]:
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [73]:
# Random Sampling
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=1)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

In [79]:
# Modelisation avec l'algorithme de l'arbre de decision
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion='entropy')

In [80]:
# Train
model.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [84]:
# Prediction
y_pred = model.predict(X_test)

In [85]:
y_test == y_pred

array([False,  True,  True, False, False])

In [86]:
#Evaluation
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[1, 0],
       [3, 1]], dtype=int64)

- True Positive
- False Positive
- False Negative
- True Negative

In [88]:
model.score(X_test, y_test)

0.4

In [90]:
model.score(X_train, y_train)

1.0